CREATE TABLE Donor (


CREATE TABLE Hospital (

    hospital_id NUMBER PRIMARY KEY,
    hospital_name VARCHAR2(100),
    city VARCHAR2(50),
    contact VARCHAR2(20)

);


CREATE TABLE Transplant (

    transplant_id NUMBER PRIMARY KEY,

    donor_id NUMBER,
    recipient_id NUMBER,
    hospital_id NUMBER,

    transplant_date DATE,
    result_status VARCHAR2(50),

    FOREIGN KEY(donor_id)
    REFERENCES Donor(donor_id),

    FOREIGN KEY(recipient_id)
    REFERENCES Recipient(recipient_id),

    FOREIGN KEY(hospital_id)
    REFERENCES Hospital(hospital_id)

);


CREATE TABLE Admins (

    admin_id NUMBER PRIMARY KEY,
    username VARCHAR2(50),
    password VARCHAR2(50)

);


CREATE TABLE Match_Log (

    match_id NUMBER PRIMARY KEY,
    donor_id NUMBER,
    recipient_id NUMBER,
    match_date DATE,

    FOREIGN KEY(donor_id)
    REFERENCES Donor(donor_id),

    FOREIGN KEY(recipient_id)
    REFERENCES Recipient(recipient_id)

);


CREATE TABLE Audit_Log (

    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    action_type VARCHAR2(20),

    donor_id NUMBER,

    action_date DATE,

    performed_by VARCHAR2(50)

);